#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Stratum Pipeline — Stage 09: Build Python Wheel (.whl)
=========================================================
LOCATION: 09_wheel/main.py
VERSION: v9 (unchanged from v8 — no bugs identified in this stage)

WHAT THIS STAGE DOES
    Zips _stratum.so (from Stage 07) together with every generated
    Python .py/.pyi file (from Stage 08) into a standard installable
    wheel. Also injects stratum/__init__.py, which provides:
      - getActivity() / get_activity()
      - setContentView() / set_content_view()
      - set_log_enabled(bool) — runtime toggle for the compile-time
        logging level baked in at Stage 07.
      - _auto_register_lifecycle() — scans your app's main.py for
        onCreate/onResume/onPause/onStop/onDestroy and wires them to the
        native Activity lifecycle automatically on import.

WHEEL NAMING
    stratum-<version>-<pytag>-<pytag>-android_<minapi>_<abi>.whl
    Match --abi and --chaquopy here to EXACTLY what you used in
    07_build/main.py, or Chaquopy on the Android side won't pick the
    wheel up for the correct device architecture / Python version.
"""

import argparse
import base64
import hashlib
import zipfile
from pathlib import Path


def sha256_record(name: str, data: bytes) -> str:
    d = base64.urlsafe_b64encode(hashlib.sha256(data).digest()).rstrip(b"=").decode()
    return f"{name},sha256={d},{len(data)}"


STRATUM_UI_PY = '''# Auto-generated by Stratum Stage 09 (ui helpers). DO NOT EDIT.
"""
High-level Python wrapper around the StratumView runtime bridge class.
See stratum-runtime/.../StratumView.java for the Java side.
"""
import uuid
import weakref
import stratum
from stratum.core.stratum_object import StratumObject, _wrap_instance


class CustomCanvasView(StratumObject):
    """Subclass this for custom 2D canvas drawing, custom touch handling,
    and (optionally) custom measurement/layout. Real View methods
    (invalidate(), setPadding(), ...) are available via attribute
    delegation to a cloned android.view.View wrapper of the SAME
    underlying Java object -- cloned so its lifetime is independent of
    this object's."""

    def __init__(self, activity=None):
        self._ptr = None
        self._key = f"view_{uuid.uuid4().hex}"
        self._view_wrapper = None

        self_ref = weakref.ref(self)

        def _on_draw(canvas_ptr):
            view = self_ref()
            if view is not None:
                view._internal_on_draw(canvas_ptr)

        def _on_measure(w_spec, h_spec):
            view = self_ref()
            return view._internal_on_measure(w_spec, h_spec) if view is not None else None

        def _on_layout(changed, l, t, r, b):
            view = self_ref()
            if view is not None:
                view._internal_on_layout(changed, l, t, r, b)

        def _on_touch(event_ptr):
            view = self_ref()
            return view._internal_on_touch(event_ptr) if view is not None else False

        stratum.register_callback(f"{self._key}#onDraw", _on_draw)
        stratum.register_callback(f"{self._key}#onMeasure", _on_measure)
        stratum.register_callback(f"{self._key}#onLayout", _on_layout)
        stratum.register_callback(f"{self._key}#onTouchEvent", _on_touch)

        native_ptr = stratum._core.create_stratum_view(self._key)
        if not native_ptr:
            self._cleanup_callbacks()
            raise RuntimeError("Stratum: failed to construct StratumView (activity not ready?)")
        super().__init__(_ptr=native_ptr)

    def _cleanup_callbacks(self):
        if self.__dict__.get("_key"):
            try:
                stratum.remove_callbacks_by_prefix(self._key)
            except Exception:
                pass

    def __del__(self):
        self._cleanup_callbacks()
        super().__del__()

    def _as_view(self):
        if self._view_wrapper is None:
            if not self._ptr:
                return None
            cloned = stratum._core.clone_ref(self._ptr)
            self._view_wrapper = _wrap_instance(cloned, "android.view.View")
        return self._view_wrapper

    def __getattr__(self, name):
        if name.startswith("_") or not self.__dict__.get("_ptr"):
            raise AttributeError(name)
        view = self._as_view()
        if view is None:
            raise AttributeError(name)
        return getattr(view, name)

    def _internal_on_draw(self, canvas_ptr):
        canvas = _wrap_instance(canvas_ptr, "android.graphics.Canvas") if isinstance(canvas_ptr, int) else canvas_ptr
        self.on_draw(canvas)

    def _internal_on_measure(self, width_spec, height_spec):
        return self.on_measure(width_spec, height_spec)

    def _internal_on_layout(self, changed, l, t, r, b):
        self.on_layout(bool(changed), l, t, r, b)

    def _internal_on_touch(self, motion_event_ptr):
        event = _wrap_instance(motion_event_ptr, "android.view.MotionEvent") if isinstance(motion_event_ptr, int) else motion_event_ptr
        return bool(self.on_touch_event(event))

    def on_draw(self, canvas):
        pass

    def on_measure(self, width_spec, height_spec):
        return None  # return [width, height] to report a custom size

    def on_layout(self, changed, left, top, right, bottom):
        pass

    def on_touch_event(self, event) -> bool:
        return False
'''

STRATUM_REFLECT_PY = '''# Auto-generated by Stratum Stage 09 (reflection escape hatch). DO NOT EDIT.
"""
Rare-path escape hatch for Java code with no generated AOT wrapper: a
class you wrote yourself in Android Studio, or one excluded by
05_resolve/targets.json. Does NOT replace the AOT wrappers -- prefer the
generated stratum.android.* classes for anything they already cover.

Built ONLY on top of stratum's own generated wrappers
(stratum.java.lang.Class / ClassLoader, stratum.java.lang.reflect.Method
/ Modifier / Array) plus two tiny native reads (get_class_name,
get_app_classloader_ptr). No changes to the AOT dispatch path, the
metadata table, or resolve_class_slots().
"""
import importlib
import stratum
from stratum.core.stratum_object import _wrap_instance

_method_cache = {}
_loader_cache = None


def _require(fqn, py_path):
    try:
        return importlib.import_module(py_path)
    except ImportError as e:
        raise ImportError(
            f"stratum.reflect needs '{fqn}' in this build. If using a "
            f"filtered/closure-mode build, add '{fqn}' to "
            f"05_resolve/targets.json and rebuild Stages 05-09."
        ) from e


def _app_class_loader():
    # Reuses the SAME cached app ClassLoader find_class() already relies
    # on internally -- available even before any Activity exists (e.g.
    # from a boot-triggered Service/Receiver).
    global _loader_cache
    if _loader_cache is not None:
        return _loader_cache
    ClassLoader = _require("java.lang.ClassLoader", "stratum.java.lang.ClassLoader").ClassLoader
    ptr = stratum._core.get_app_classloader_ptr()
    if not ptr:
        raise RuntimeError("stratum.reflect: app ClassLoader not ready yet")
    _loader_cache = ClassLoader(_ptr=ptr)
    return _loader_cache


def _forname(class_name):
    # 3-arg Class.forName(name, initialize, loader): a bare 1-arg
    # Class.forName(name) called through JNI has no Java caller frame,
    # so ART resolves it against the BOOT classloader and cannot see
    # your own app/custom classes. The explicit app-classloader form
    # fixes that and still finds every platform/SDK class fine.
    Class = _require("java.lang.Class", "stratum.java.lang.Class").Class
    return Class.forName(class_name, True, _app_class_loader())


def _wrap_array(raw_list, element_fqn):
    return [_wrap_instance(p, element_fqn) for p in raw_list if p]


def _type_matches(param_class, value):
    name = param_class.getName()
    if isinstance(value, bool):
        return name in ("boolean", "java.lang.Boolean")
    if isinstance(value, int):
        return name in ("int", "long", "short", "byte",
                         "java.lang.Integer", "java.lang.Long",
                         "java.lang.Short", "java.lang.Byte")
    if isinstance(value, float):
        return name in ("float", "double", "java.lang.Float", "java.lang.Double")
    if isinstance(value, str):
        return name in ("java.lang.String", "java.lang.CharSequence")
    if value is None:
        return not param_class.isPrimitive()
    if hasattr(value, "_ptr"):
        return bool(param_class.isInstance(value))
    return False


def _resolve(cls_wrapper, class_name, method_name, args, want_static):
    key = (class_name, method_name, len(args), tuple(type(a).__name__ for a in args))
    cached = _method_cache.get(key)
    if cached is not None:
        return cached

    Modifier = _require("java.lang.reflect.Modifier", "stratum.java.lang.reflect.Modifier").Modifier
    candidates = _wrap_array(cls_wrapper.getMethods(), "java.lang.reflect.Method")
    matches = []
    for m in candidates:
        if m.getName() != method_name:
            continue
        if bool(Modifier.isStatic(m.getModifiers())) != want_static:
            continue
        params = _wrap_array(m.getParameterTypes(), "java.lang.Class")
        if len(params) != len(args):
            continue
        if all(_type_matches(p, a) for p, a in zip(params, args)):
            matches.append(m)

    if not matches:
        kind = "static method" if want_static else "method"
        raise TypeError(f"No matching {kind} '{method_name}' with {len(args)} argument(s) on {class_name}")

    chosen = matches[0]
    _method_cache[key] = chosen
    return chosen


def _invoke(method, target, args):
    packed = stratum.to_java_array(list(args), "java.lang.Object") if args else None
    try:
        result = method.invoke(target, packed)
    except Exception as e:
        raise RuntimeError(f"Java call failed: {e}") from e
    return stratum.to_py(result)


def call_java_static(class_name: str, method_name: str, *args):
    """Call a STATIC Java method by fully-qualified class name."""
    cls = _forname(class_name)
    method = _resolve(cls, class_name, method_name, args, want_static=True)
    return _invoke(method, None, args)


def call_java_method(obj, method_name: str, *args):
    """Call an INSTANCE method, resolved against the object's REAL
    runtime class (so this works on your own subclasses too)."""
    ptr = getattr(obj, "_ptr", None)
    if not ptr:
        raise ValueError("call_java_method: object has no live Java reference")
    class_name = stratum._core.get_class_name(ptr)
    if not class_name:
        raise RuntimeError("call_java_method: could not determine runtime class")
    cls = _forname(class_name)
    method = _resolve(cls, class_name, method_name, args, want_static=False)
    return _invoke(method, obj, args)


def call_java(target, method_name: str, *args):
    """Universal entry point:
    - target is a class name string (e.g. 'com.example.Helper') -> STATIC call.
    - target is an existing wrapped object (has ._ptr)           -> INSTANCE call.
    """
    if isinstance(target, str):
        return call_java_static(target, method_name, *args)
    elif hasattr(target, "_ptr"):
        return call_java_method(target, method_name, *args)
    else:
        raise TypeError(f"call_java: target must be a class name (str) or a wrapped object, got {type(target)}")
'''



INIT_PY = '''# Stratum Runtime Entry Point. Auto-generated. DO NOT EDIT.
# Optional dynamic-mode class loader (see 08_pyi_emit --mode dynamic).
# In a static-mode wheel (the default, unchanged pipeline) stratum/_dynamic.py
# simply doesn't exist in the wheel, ImportError is swallowed, and nothing
# below this block changes behavior at all.
try:
    from . import _dynamic as _stratum_dynamic
    _stratum_dynamic.install()
except ImportError:
    pass

from . import _stratum as _core
from stratum.core.stratum_object import StratumObject
import importlib
import sys


def getActivity():
    """Return the current Android Activity, or None before onCreate."""
    ptr = _core.get_activity_ptr()
    if not ptr:
        return None
    from stratum.android.app.Activity import Activity
    return Activity(_ptr=ptr)


get_activity = getActivity
stratum_get_activity = getActivity


def stratum_cast(obj, target_cls):
    """Safely cast an object or pointer to target_cls with JNI IsInstanceOf verification."""
    if obj is None:
        return None
    return target_cls.from_ptr(obj)


stratum_cast_to = stratum_cast


def setContentView(activity, view) -> None:
    """Mount a View as the Activity's root content view."""
    act_ptr = getattr(activity, "_ptr", activity)
    view_ptr = getattr(view, "_ptr", view)
    _core.set_content_view(act_ptr, view_ptr)


set_content_view = setContentView


def allocate_direct_buffer(capacity: int):
    """Allocate an off-heap direct java.nio.ByteBuffer."""
    ptr = _core.allocate_direct_buffer(capacity)
    if not ptr:
        return None
    from stratum.core.stratum_object import _wrap_instance
    return _wrap_instance(ptr, "java.nio.ByteBuffer")


def surface_to_native_window(surface) -> int:
    """Acquire an ANativeWindow* pointer (as an integer) from an android.view.Surface."""
    s_ptr = getattr(surface, "_ptr", surface)
    return _core.surface_to_native_window(s_ptr)


def release_native_window(win_ptr: int) -> None:
    """Release an ANativeWindow* handle previously acquired."""
    _core.release_native_window(win_ptr)


def to_java(obj):
    """Recursively converts Python data (dict, list, int, float, bool, str, bytes)
    into a real Java object (HashMap, ArrayList, Boxed primitives, byte[]).
    Existing StratumObject instances retain their underlying Java reference."""
    if obj is None:
        return None
    if hasattr(obj, "_ptr"):
        return obj
    ptr = _core.to_java(obj)
    if not ptr:
        return None
    return StratumObject(_ptr=ptr)


def to_py(obj):
    """Recursively converts Java objects (Map, List, Bundle, boxed primitives,
    and arrays) into native Python data (dict, list, int, float, bool, str, bytes).
    Non-data Java objects are wrapped into typed StratumObject instances."""
    if obj is None:
        return None
    # 100% DEFENSIVE GUARD: If the object does not have _ptr, it is ALREADY native
    # Python data (e.g. an int, bool, float, str, list, dict). Never treat a bare
    # Python numeric value as a raw JNI memory address!
    if not hasattr(obj, "_ptr"):
        return obj
    ptr = getattr(obj, "_ptr", None)
    if not isinstance(ptr, int) or ptr == 0:
        return None
    return _core.to_py(ptr)


def register_function(name: str, fn) -> None:
    """Registers a Python function so Java can call it via
    StratumRuntimeLookup.callPython(name, ...). Thin wrapper over the
    existing register_callback -- no new native binding needed."""
    register_callback(f"app#{name}", fn)


def export(fn_or_name):
    """Decorator to expose a Python function to Java.

    Usage:
        @stratum.export
        def calculate_score(points, multiplier):
            return points * multiplier
    """
    if callable(fn_or_name):
        register_function(fn_or_name.__name__, fn_or_name)
        return fn_or_name
    def decorator(fn):
        register_function(fn_or_name, fn)
        return fn
    return decorator


def to_java_array(items, component_type: str):
    """Converts a Python list into a strongly-typed native Java array
    (T[]), for APIs whose signature is erased to Object (e.g.
    Camera2's CaptureRequest.set(Key<T>, T)), and used internally by
    stratum.reflect's call_java()/call_java_method().

    component_type: Java FQN of the element type (required -- guessing
    it from list contents risks a ClassCastException on an empty or
    mixed-type list).
    """
    Class = importlib.import_module("stratum.java.lang.Class").Class
    Array = importlib.import_module("stratum.java.lang.reflect.Array").Array
    loader_ptr = _core.get_app_classloader_ptr()
    if loader_ptr:
        ClassLoader = importlib.import_module("stratum.java.lang.ClassLoader").ClassLoader
        comp_cls = Class.forName(component_type, True, ClassLoader(_ptr=loader_ptr))
    else:
        comp_cls = Class.forName(component_type)
    arr = Array.newInstance(comp_cls, len(items))
    for i, item in enumerate(items):
        Array.set(arr, i, item)
    return arr


def remove_callback(key: str) -> None:
    """Release a stored Python callback (listener/adapter) by its key,
    if you tracked it. Reduces the g_callbacks map growth flagged by the
    logcat warning that fires once it exceeds ~10,000 live entries."""
    _core.remove_callback(key)


def remove_callbacks_by_prefix(prefix: str) -> int:
    """Remove all stored callbacks matching a given prefix."""
    return _core.remove_callbacks_by_prefix(prefix)


def callback_count() -> int:
    """Number of Python callbacks currently retained by the native side."""
    return _core.stratum_callback_count()


def register_callback(key: str, fn) -> None:
    """Bind a Python callable to a native callback key (or 'key#method').
    Used internally by stratum.ui.CustomCanvasView."""
    _core.register_callback(key, fn)


def create_stratum_view(key: str):
    """Construct a native com.stratum.runtime.StratumView bound to `key`.
    Prefer stratum.ui.CustomCanvasView instead of calling this directly."""
    ptr = _core.create_stratum_view(key)
    if not ptr:
        return None
    from stratum.core.stratum_object import _wrap_instance
    return _wrap_instance(ptr, "android.view.View")

_main_handler = None

def run_on_ui_thread(fn, *args, **kwargs) -> None:
    """Posts a callable to Android's Main Looper (UI thread). Required
    before touching any View from a background thread, timer, sensor
    callback, or network response -- Android throws
    CalledFromWrongThreadException otherwise. Lazily imports
    android.os.Handler/Looper, so this costs nothing if never called."""
    global _main_handler
    if _main_handler is None:
        from stratum.android.os.Handler import Handler
        from stratum.android.os.Looper import Looper
        _main_handler = Handler(Looper.getMainLooper())

    def _runner():
        fn(*args, **kwargs)

    _main_handler.post(_runner)


def ui_thread(fn):
    """Decorator: always runs the wrapped function on the Android UI thread."""
    def wrapper(*args, **kwargs):
        run_on_ui_thread(fn, *args, **kwargs)
    return wrapper



def set_log_enabled(enabled: bool) -> None:
    """Toggle runtime logging. Only has any effect if this .so was
    compiled with --log-level 1 or 2 in Stage 07 — level 0 (the default)
    strips all logging code at compile time, so this call is a silent
    no-op on a production build."""
    _core.set_log_enabled(enabled)



def _auto_register_lifecycle() -> None:
    try:
        main = sys.modules.get("main") or importlib.import_module("main")
    except Exception:
        return
    for name in ("onCreate", "onResume", "onPause", "onStop", "onDestroy"):
        fn = getattr(main, name, None)
        if callable(fn):
            _core.set_lifecycle_callback(name, fn)


try:
    _auto_register_lifecycle()
except Exception:
    pass
'''


def main():
    ap = argparse.ArgumentParser(description="Stratum Stage 09 - Build Wheel (v9)")
    ap.add_argument("--so", required=True, help="Path to compiled _stratum.so")
    ap.add_argument("--py-src", required=True, help="Path to 08_pyi_emit/output/")
    ap.add_argument("--output", required=True, help="Output destination folder")
    ap.add_argument("--version", default="0.9.0")
    ap.add_argument("--min-api", default="24")
    ap.add_argument("--abi", default="arm64-v8a")
    ap.add_argument("--chaquopy", default="3.12.0-0")
    ap.add_argument("--include-reflect", choices=["yes", "no"], default="yes",
                    help="yes (default) packs stratum/reflect.py, the rare-path "
                        "call_java()/call_java_method() escape hatch. Zero AOT "
                        "overhead when unused; set 'no' to omit it entirely.")
    ap.add_argument("--include-pyi", choices=["yes", "no"], default="yes",
                     help="yes (default, unchanged v9 behavior) packs .pyi stub "
                          "files into the wheel too. no drops them from the "
                          "runtime wheel (they're IDE-only, never imported at "
                          "runtime) to shrink the .whl — use for production/"
                          "release builds. Works with either Stage 08 --mode.")
    args = ap.parse_args()

    print("=" * 70)
    print("  STRATUM PIPELINE — STAGE 09 (WHEEL) v9")
    print("=" * 70)

    so_path = Path(args.so)
    py_dir = Path(args.py_src)
    out_dir = Path(args.output)
    out_dir.mkdir(parents=True, exist_ok=True)

    py_ver = ".".join(args.chaquopy.split(".")[:2])
    py_tag = "cp" + py_ver.replace(".", "")
    abi_tag = args.abi.replace("-", "_")
    ver_safe = args.version.replace("-", "_")

    wheel_name = f"stratum-{ver_safe}-{py_tag}-{py_tag}-android_{args.min_api}_{abi_tag}.whl"
    wheel_path = out_dir / wheel_name
    dist_info = f"stratum-{ver_safe}.dist-info"
    records = []

    with zipfile.ZipFile(wheel_path, "w", compression=zipfile.ZIP_DEFLATED) as zf:
        init_data = INIT_PY.encode("utf-8")
        zf.writestr("stratum/__init__.py", init_data)
        records.append(sha256_record("stratum/__init__.py", init_data))

        ui_data = STRATUM_UI_PY.encode("utf-8")
        zf.writestr("stratum/ui.py", ui_data)
        records.append(sha256_record("stratum/ui.py", ui_data))

        if args.include_reflect == "yes":
            reflect_data = STRATUM_REFLECT_PY.encode("utf-8")
            zf.writestr("stratum/reflect.py", reflect_data)
            records.append(sha256_record("stratum/reflect.py", reflect_data))

        so_data = so_path.read_bytes()
        so_info = zipfile.ZipInfo("stratum/_stratum.so")
        so_info.external_attr = 0o755 << 16  # rwxr-xr-x — writestr() defaults to 0600, which
                                              # makes dlopen() refuse to map it on-device with
                                              # UnsatisfiedLinkError: ... Permission denied
        so_info.compress_type = zipfile.ZIP_DEFLATED
        zf.writestr(so_info, so_data)
        records.append(sha256_record("stratum/_stratum.so", so_data))

        allowed_suffixes = {".py"} if args.include_pyi == "no" else {".py", ".pyi"}
        for f in sorted(py_dir.rglob("*")):
            if not f.is_file():
                continue
            # .py / .pyi as before (.pyi optionally dropped via --include-pyi no).
            # _meta.json.gz is the new dynamic-mode metadata blob (08_pyi_emit
            # --mode dynamic) — it has neither suffix, so it needs its own check.
            is_meta_blob = f.name == "_meta.json.gz"
            if f.suffix not in allowed_suffixes and not is_meta_blob:
                continue
            rel = f.relative_to(py_dir)
            entry = rel.as_posix()
            data = f.read_bytes()
            zf.writestr(entry, data)
            records.append(sha256_record(entry, data))

        wheel_meta = (
            f"Wheel-Version: 1.0\nGenerator: stratum\nRoot-Is-Purelib: false\n"
            f"Tag: {py_tag}-{py_tag}-android_{args.min_api}_{abi_tag}\n"
        ).encode()
        zf.writestr(f"{dist_info}/WHEEL", wheel_meta)
        records.append(sha256_record(f"{dist_info}/WHEEL", wheel_meta))

        metadata = (
            f"Metadata-Version: 2.1\nName: stratum\nVersion: {ver_safe}\n"
            f"Summary: Python bridge to Android native API\nRequires-Python: >={py_ver}\n"
        ).encode()
        zf.writestr(f"{dist_info}/METADATA", metadata)
        records.append(sha256_record(f"{dist_info}/METADATA", metadata))

        record_entry = f"{dist_info}/RECORD"
        zf.writestr(record_entry, "\n".join(records) + f"\n{record_entry},,\n")

    size_mb = wheel_path.stat().st_size / (1024 * 1024)
    print(f"-> Packaged: {wheel_path.name} ({size_mb:.2f} MB)")


if __name__ == "__main__":
    main()